In [40]:
import pandas as pd
import numpy as np
import math
import numpy as np
from scipy.stats import shapiro 
from scipy.stats import lognorm

In [41]:
data_AU = pd.read_csv('AU_features.csv')

In [42]:
del data_AU['Unnamed: 0']
del data_AU['index']
del data_AU['record']

In [43]:
del data_AU['patient']
del data_AU['timestamp_start']
del data_AU['timestamp_end']

In [44]:
data_AU = data_AU.fillna(data_AU.mean())

In [45]:
data_AU_HC = data_AU[data_AU['diagnosis']==0]

In [46]:
data_AU_dep = data_AU[data_AU['diagnosis']==1]

In [47]:
del data_AU_HC['diagnosis']
del data_AU_dep['diagnosis']

In [48]:
features = list(data_AU_dep.columns)

# Check normality of the data

In [49]:
HC_values = []
dep_values = []

In [50]:
for feature in features:
    HC_values.append(shapiro(data_AU_HC[feature])[1])
    dep_values.append(shapiro(data_AU_dep[feature])[1])

C:\Users\skiju\anaconda3\Lib\site-packages\scipy\stats\_morestats.py:1879: UserWarning: Input data for shapiro has range zero. The results may not be accurate.
  warnings.warn("Input data for shapiro has range zero. The results "

In [12]:
normality_distribution = pd.DataFrame(columns=['features', 'HC_p', 'dep_p'])

In [13]:
normality_distribution['features'] = features

In [14]:
normality_distribution['HC_p'] =HC_values

In [15]:
normality_distribution['dep_p'] = dep_values

In [16]:
normality_distribution[normality_distribution['HC_p']<=0.05]

                           features      HC_p     dep_p
0          AU01_mid_Absolute energy  0.001671  0.000070
1     AU01_mid_Area under the curve  0.002916  0.000141
2          AU01_mid_Autocorrelation  0.000005  0.000722
3            AU01_mid_Average power  0.041854  0.496138
4                 AU01_mid_Centroid  0.000169  0.004688
...                             ...       ...       ...
7095                   AU06_eve_rsd  0.000155  0.959659
7096                   AU07_eve_rsd  0.000046  0.459381
7097                   AU10_eve_rsd  0.009519  0.785761
7098                   AU12_eve_rsd  0.000057  0.006704
7103                   AU24_eve_rsd  0.043057  0.510090

[4983 rows x 3 columns]

In [17]:
normality_distribution[normality_distribution['dep_p']<=0.05]

                              features      HC_p     dep_p
0             AU01_mid_Absolute energy  0.001671  0.000070
1        AU01_mid_Area under the curve  0.002916  0.000141
2             AU01_mid_Autocorrelation  0.000005  0.000722
4                    AU01_mid_Centroid  0.000169  0.004688
5     AU01_mid_ECDF Percentile Count_0  0.000194  0.012516
...                                ...       ...       ...
7086                  AU12_eve_app_ent  0.013827  0.010803
7088                  AU15_eve_app_ent  0.123660  0.004266
7090                  AU23_eve_app_ent  0.489309  0.014334
7098                      AU12_eve_rsd  0.000057  0.006704
7099                      AU14_eve_rsd  0.629831  0.008448

[3400 rows x 3 columns]

# Since the majority of the features are not normally distributed, Pearson correlation will be calculated

In [51]:
import scipy.stats as stats

In [53]:
data_AU_HC
data_AU_dep

,AU01_mid_Absolute energy,AU01_mid_Area under the curve,AU01_mid_Autocorrelation,AU01_mid_Average power,AU01_mid_Centroid,AU01_mid_ECDF Percentile Count_0,AU01_mid_ECDF Percentile Count_1,AU01_mid_ECDF Percentile_0,AU01_mid_ECDF Percentile_1,AU01_mid_ECDF_0,...,AU04_eve_rsd,AU06_eve_rsd,AU07_eve_rsd,AU10_eve_rsd,AU12_eve_rsd,AU14_eve_rsd,AU15_eve_rsd,AU17_eve_rsd,AU23_eve_rsd,AU24_eve_rsd
2,11.415247,0.220840,2.000000,2.875377,1.133316,79.000000,318.000000,0.000820,0.050790,0.002513,...,265.374413,121.008673,67.176427,179.301774,89.136093,96.213302,138.309344,69.726973,135.622399,202.271039
4,21.142705,0.263578,1.000000,35.237842,0.239713,12.000000,48.000000,0.016091,0.882381,0.016393,...,116.988466,134.024675,46.498004,202.483565,118.604478,92.273881,106.845779,70.164313,109.443031,191.562723
5,20.994168,0.265975,4.000000,29.991668,0.394627,14.000000,56.000000,0.011960,0.858960,0.014085,...,291.131247,162.944912,71.969314,400.045107,112.831481,55.994326,136.362200,128.327725,247.829012,716.936198
10,9.122883,0.145782,2.000000,6.291643,1.045863,29.000000,116.000000,0.000145,0.086164,0.006849,...,176.010829,205.710660,80.940490,334.540653,255.280704,232.573141,224.974399,111.707370,315.072176,756.285165
13,103.357981,1.222127,17.000000,51.421881,0.816389,40.000000,161.000000,0.054901,0.933992,0.004950,...,233.828141,133.229961,74.018833,382.003612,112.218930,111.523354,170.431072,96.982193,148.565087,201.637073
14,143.395653,2.238986,3.000000,12.121357,6.133693,236.000000,947.000000,0.001132,0.413815,0.000845,...,199.171956,147.300449,70.534243,299.204224,151.707252,110.115983,127.825284,53.339761,159.486032,570.492425
15,165.125454,2.305494,3.000000,16.815219,3.968694,196.000000,786.000000,0.001272,0.566184,0.001017,...,251.089074,151.898807,83.133014,289.405013,155.340625,99.134680,124.391735,58.558246,137.297885,433.001841
16,291.831223,3.855189,18.526316,20.541164,6.557825,268.473684,1075.184211,0.009091,0.552215,0.002808,...,189.499509,124.558952,60.143923,236.841595,146.072237,118.307017,156.485998,68.561154,157.643202,515.987555
17,291.831223,3.855189,18.526316,20.541164,6.557825,268.473684,1075.184211,0.009091,0.552215,0.002808,...,189.499509,124.558952,60.143923,236.841595,146.072237,118.307017,156.485998,68.561154,157.643202,515.987555
21,42.924443,0.610312,4.000000,19.780849,0.913781,43.000000,174.000000,0.002914,0.634446,0.004587,...,144.766483,62.805806,39.511453,88.369386,84.034607,90.932349,125.965679,54.331211,102.688696,681.279367
24,138.596402,2.612807,26.000000,6.764100,7.212719,410.000000,1640.000000,0.000020,0.194067,0.000488,...,59.130596,180.889244,31.778058,284.477056,170.252081,54.163010,40.953834,18.677663,61.513525,586.987408
25,115.728873,2.464224,3.000000,9.676327,6.559235,239.000000,957.000000,0.025575,0.375248,0.000835,...,75.472210,188.103775,59.787927,370.667139,356.622469,96.086324,63.146310,18.664397,98.009214,1022.233854
31,1416.620799,16.535962,4.000000,41.288860,17.975948,686.000000,2745.000000,0.006553,0.986350,0.000291,...,105.946971,93.830646,68.416012,191.139851,176.419904,235.518350,269.925095,96.137536,179.087188,1306.713779
32,1160.854156,14.431542,4.000000,33.726152,16.810768,688.000000,2754.000000,0.007423,0.940743,0.000290,...,114.778733,116.556963,86.600239,200.048984,161.740007,192.335126,199.418447,88.729381,199.037527,881.704162

In [54]:
data_AU_dep[features[0]]

2       11.415247
4       21.142705
5       20.994168
10       9.122883
13     103.357981
14     143.395653
15     165.125454
16     291.831223
17     291.831223
21      42.924443
24     138.596402
25     115.728873
31    1416.620799
32    1160.854156
Name: AU01_mid_Absolute energy, dtype: float64

In [55]:
data_AU_test = data_AU

In [56]:
y = data_AU['diagnosis']

In [57]:
del data_AU_test['diagnosis']

In [62]:
r_value = []
p_value = []
mean_value_HC = []
std_value_HC = []
mean_value_dep = []
std_value_dep = []

In [63]:
features = list(data_AU_test.columns)

In [64]:
features

['AU01_mid_Absolute energy',
 'AU01_mid_Area under the curve',
 'AU01_mid_Autocorrelation',
 'AU01_mid_Average power',
 'AU01_mid_Centroid',
 'AU01_mid_ECDF Percentile Count_0',
 'AU01_mid_ECDF Percentile Count_1',
 'AU01_mid_ECDF Percentile_0',
 'AU01_mid_ECDF Percentile_1',
 'AU01_mid_ECDF_0',
 'AU01_mid_ECDF_1',
 'AU01_mid_ECDF_2',
 'AU01_mid_ECDF_3',
 'AU01_mid_ECDF_4',
 'AU01_mid_ECDF_5',
 'AU01_mid_ECDF_6',
 'AU01_mid_ECDF_7',
 'AU01_mid_ECDF_8',
 'AU01_mid_ECDF_9',
 'AU01_mid_Entropy',
 'AU01_mid_Fundamental frequency',
 'AU01_mid_Histogram mode',
 'AU01_mid_Human range energy',
 'AU01_mid_Interquartile range',
 'AU01_mid_Kurtosis',
 'AU01_mid_LPCC_0',
 'AU01_mid_LPCC_1',
 'AU01_mid_LPCC_10',
 'AU01_mid_LPCC_11',
 'AU01_mid_LPCC_2',
 'AU01_mid_LPCC_3',
 'AU01_mid_LPCC_4',
 'AU01_mid_LPCC_5',
 'AU01_mid_LPCC_6',
 'AU01_mid_LPCC_7',
 'AU01_mid_LPCC_8',
 'AU01_mid_LPCC_9',
 'AU01_mid_MFCC_0',
 'AU01_mid_MFCC_1',
 'AU01_mid_MFCC_10',
 'AU01_mid_MFCC_11',
 'AU01_mid_MFCC_2',
 'AU01_mid_MFCC_3',
 'AU01_mid_MFCC_4',
 'AU01_mid_MFCC_5',
 'AU01_mid_MFCC_6',
 'AU01_mid_MFCC_7',
 'AU01_mid_MFCC_8',
 'AU01_mid_MFCC_9',
 'AU01_mid_Max',
 'AU01_mid_Max power spectrum',
 'AU01_mid_Maximum frequency',
 'AU01_mid_Mean',
 'AU01_mid_Mean absolute deviation',
 'AU01_mid_Mean absolute diff',
 'AU01_mid_Mean diff',
 'AU01_mid_Median',
 'AU01_mid_Median absolute deviation',
 'AU01_mid_Median absolute diff',
 'AU01_mid_Median diff',
 'AU01_mid_Median frequency',
 'AU01_mid_Min',
 'AU01_mid_Negative turning points',
 'AU01_mid_Neighbourhood peaks',
 'AU01_mid_Peak to peak distance',
 'AU01_mid_Positive turning points',
 'AU01_mid_Power bandwidth',
 'AU01_mid_Root mean square',
 'AU01_mid_Signal distance',
 'AU01_mid_Skewness',
 'AU01_mid_Slope',
 'AU01_mid_Spectral centroid',
 'AU01_mid_Spectral decrease',
 'AU01_mid_Spectral distance',
 'AU01_mid_Spectral entropy',
 'AU01_mid_Spectral kurtosis',
 'AU01_mid_Spectral positive turning points',
 'AU01_mid_Spectral roll-off',
 'AU01_mid_Spectral roll-on',
 'AU01_mid_Spectral skewness',
 'AU01_mid_Spectral slope',
 'AU01_mid_Spectral spread',
 'AU01_mid_Spectral variation',
 'AU01_mid_Standard deviation',
 'AU01_mid_Sum absolute diff',
 'AU01_mid_Variance',
 'AU01_mid_Wavelet absolute mean_12.5Hz',
 'AU01_mid_Wavelet absolute mean_2.78Hz',
 'AU01_mid_Wavelet absolute mean_25.0Hz',
 'AU01_mid_Wavelet absolute mean_3.12Hz',
 'AU01_mid_Wavelet absolute mean_3.57Hz',
 'AU01_mid_Wavelet absolute mean_4.17Hz',
 'AU01_mid_Wavelet absolute mean_5.0Hz',
 'AU01_mid_Wavelet absolute mean_6.25Hz',
 'AU01_mid_Wavelet absolute mean_8.33Hz',
 'AU01_mid_Wavelet energy_12.5Hz',
 'AU01_mid_Wavelet energy_2.78Hz',
 'AU01_mid_Wavelet energy_25.0Hz',
 'AU01_mid_Wavelet energy_3.12Hz',
 'AU01_mid_Wavelet energy_3.57Hz',
 'AU01_mid_Wavelet energy_4.17Hz',
 'AU01_mid_Wavelet energy_5.0Hz',
 'AU01_mid_Wavelet energy_6.25Hz',
 'AU01_mid_Wavelet energy_8.33Hz',
 'AU01_mid_Wavelet entropy',
 'AU01_mid_Wavelet standard deviation_12.5Hz',
 'AU01_mid_Wavelet standard deviation_2.78Hz',
 'AU01_mid_Wavelet standard deviation_25.0Hz',
 'AU01_mid_Wavelet standard deviation_3.12Hz',
 'AU01_mid_Wavelet standard deviation_3.57Hz',
 'AU01_mid_Wavelet standard deviation_4.17Hz',
 'AU01_mid_Wavelet standard deviation_5.0Hz',
 'AU01_mid_Wavelet standard deviation_6.25Hz',
 'AU01_mid_Wavelet standard deviation_8.33Hz',
 'AU01_mid_Wavelet variance_12.5Hz',
 'AU01_mid_Wavelet variance_2.78Hz',
 'AU01_mid_Wavelet variance_25.0Hz',
 'AU01_mid_Wavelet variance_3.12Hz',
 'AU01_mid_Wavelet variance_3.57Hz',
 'AU01_mid_Wavelet variance_4.17Hz',
 'AU01_mid_Wavelet variance_5.0Hz',
 'AU01_mid_Wavelet variance_6.25Hz',
 'AU01_mid_Wavelet variance_8.33Hz',
 'AU01_mid_Zero crossing rate',
 'AU02_mid_Absolute energy',
 'AU02_mid_Area under the curve',
 'AU02_mid_Autocorrelation',
 'AU02_mid_Average power',
 'AU02_mid_Centroid',
 'AU02_mid_ECDF Percentile Count_0',
 'AU02_mid_ECDF Percentile Count_1',
 'AU02_mid_ECDF Percentile_0',
 'AU02_mid_ECDF Percentile_1',
 'AU02_mid_ECDF_0',
 'AU02_mid_ECDF_1',
 'AU02_mid_ECDF_2',
 'AU02_mid_ECDF_3',
 'AU02_mid_ECDF_4',
 'AU02_mid_ECDF_5',
 'AU02_mid_ECDF_6',
 'AU02_mid_ECDF_7',
 'AU02_mid_ECDF_8',
 'AU02_mid_ECDF_9',
 'AU02_mid_Entropy',
 'AU02_mid_Fundamental frequency',
 'AU02_mid_Histogram mode',
 'AU02_mid_Human range energy',
 'AU02_mid_Interquartile range',
 'AU02_mid_Kurtosis',
 'AU02_mid_LPCC_0',
 'AU02_mid_LPCC_1',
 'AU02_mid_LPCC_10',
 'AU02_mid_LPCC_11',
 'AU02_mid_LPCC_2',
 'AU02_mid_LPCC_3',
 'AU02_mid_LPCC_4',
 'AU02_mid_LPCC_5',
 'AU02_mid_LPCC_6',
 'AU02_mid_LPCC_7',
 'AU02_mid_LPCC_8',
 'AU02_mid_LPCC_9',
 'AU02_mid_MFCC_0',
 'AU02_mid_MFCC_1',
 'AU02_mid_MFCC_10',
 'AU02_mid_MFCC_11',
 'AU02_mid_MFCC_2',
 'AU02_mid_MFCC_3',
 'AU02_mid_MFCC_4',
 'AU02_mid_MFCC_5',
 'AU02_mid_MFCC_6',
 'AU02_mid_MFCC_7',
 'AU02_mid_MFCC_8',
 'AU02_mid_MFCC_9',
 'AU02_mid_Max',
 'AU02_mid_Max power spectrum',
 'AU02_mid_Maximum frequency',
 'AU02_mid_Mean',
 'AU02_mid_Mean absolute deviation',
 'AU02_mid_Mean absolute diff',
 'AU02_mid_Mean diff',
 'AU02_mid_Median',
 'AU02_mid_Median absolute deviation',
 'AU02_mid_Median absolute diff',
 'AU02_mid_Median diff',
 'AU02_mid_Median frequency',
 'AU02_mid_Min',
 'AU02_mid_Negative turning points',
 'AU02_mid_Neighbourhood peaks',
 'AU02_mid_Peak to peak distance',
 'AU02_mid_Positive turning points',
 'AU02_mid_Power bandwidth',
 'AU02_mid_Root mean square',
 'AU02_mid_Signal distance',
 'AU02_mid_Skewness',
 'AU02_mid_Slope',
 'AU02_mid_Spectral centroid',
 'AU02_mid_Spectral decrease',
 'AU02_mid_Spectral distance',
 'AU02_mid_Spectral entropy',
 'AU02_mid_Spectral kurtosis',
 'AU02_mid_Spectral positive turning points',
 'AU02_mid_Spectral roll-off',
 'AU02_mid_Spectral roll-on',
 'AU02_mid_Spectral skewness',
 'AU02_mid_Spectral slope',
 'AU02_mid_Spectral spread',
 'AU02_mid_Spectral variation',
 'AU02_mid_Standard deviation',
 'AU02_mid_Sum absolute diff',
 'AU02_mid_Variance',
 'AU02_mid_Wavelet absolute mean_12.5Hz',
 'AU02_mid_Wavelet absolute mean_2.78Hz',
 'AU02_mid_Wavelet absolute mean_25.0Hz',
 'AU02_mid_Wavelet absolute mean_3.12Hz',
 'AU02_mid_Wavelet absolute mean_3.57Hz',
 'AU02_mid_Wavelet absolute mean_4.17Hz',
 'AU02_mid_Wavelet absolute mean_5.0Hz',
 'AU02_mid_Wavelet absolute mean_6.25Hz',
 'AU02_mid_Wavelet absolute mean_8.33Hz',
 'AU02_mid_Wavelet energy_12.5Hz',
 'AU02_mid_Wavelet energy_2.78Hz',
 'AU02_mid_Wavelet energy_25.0Hz',
 'AU02_mid_Wavelet energy_3.12Hz',
 'AU02_mid_Wavelet energy_3.57Hz',
 'AU02_mid_Wavelet energy_4.17Hz',
 'AU02_mid_Wavelet energy_5.0Hz',
 'AU02_mid_Wavelet energy_6.25Hz',
 'AU02_mid_Wavelet energy_8.33Hz',
 'AU02_mid_Wavelet entropy',
 'AU02_mid_Wavelet standard deviation_12.5Hz',
 'AU02_mid_Wavelet standard deviation_2.78Hz',
 'AU02_mid_Wavelet standard deviation_25.0Hz',
 'AU02_mid_Wavelet standard deviation_3.12Hz',
 'AU02_mid_Wavelet standard deviation_3.57Hz',
 'AU02_mid_Wavelet standard deviation_4.17Hz',
 'AU02_mid_Wavelet standard deviation_5.0Hz',
 'AU02_mid_Wavelet standard deviation_6.25Hz',
 'AU02_mid_Wavelet standard deviation_8.33Hz',
 'AU02_mid_Wavelet variance_12.5Hz',
 'AU02_mid_Wavelet variance_2.78Hz',
 'AU02_mid_Wavelet variance_25.0Hz',
 'AU02_mid_Wavelet variance_3.12Hz',
 'AU02_mid_Wavelet variance_3.57Hz',
 'AU02_mid_Wavelet variance_4.17Hz',
 'AU02_mid_Wavelet variance_5.0Hz',
 'AU02_mid_Wavelet variance_6.25Hz',
 'AU02_mid_Wavelet variance_8.33Hz',
 'AU02_mid_Zero crossing rate',
 'AU04_mid_Absolute energy',
 'AU04_mid_Area under the curve',
 'AU04_mid_Autocorrelation',
 'AU04_mid_Average power',
 'AU04_mid_Centroid',
 'AU04_mid_ECDF Percentile Count_0',
 'AU04_mid_ECDF Percentile Count_1',
 'AU04_mid_ECDF Percentile_0',
 'AU04_mid_ECDF Percentile_1',
 'AU04_mid_ECDF_0',
 'AU04_mid_ECDF_1',
 'AU04_mid_ECDF_2',
 'AU04_mid_ECDF_3',
 'AU04_mid_ECDF_4',
 'AU04_mid_ECDF_5',
 'AU04_mid_ECDF_6',
 'AU04_mid_ECDF_7',
 'AU04_mid_ECDF_8',
 'AU04_mid_ECDF_9',
 'AU04_mid_Entropy',
 'AU04_mid_Fundamental frequency',
 'AU04_mid_Histogram mode',
 'AU04_mid_Human range energy',
 'AU04_mid_Interquartile range',
 'AU04_mid_Kurtosis',
 'AU04_mid_LPCC_0',
 'AU04_mid_LPCC_1',
 'AU04_mid_LPCC_10',
 'AU04_mid_LPCC_11',
 'AU04_mid_LPCC_2',
 'AU04_mid_LPCC_3',
 'AU04_mid_LPCC_4',
 'AU04_mid_LPCC_5',
 'AU04_mid_LPCC_6',
 'AU04_mid_LPCC_7',
 'AU04_mid_LPCC_8',
 'AU04_mid_LPCC_9',
 'AU04_mid_MFCC_0',
 'AU04_mid_MFCC_1',
 'AU04_mid_MFCC_10',
 'AU04_mid_MFCC_11',
 'AU04_mid_MFCC_2',
 'AU04_mid_MFCC_3',
 'AU04_mid_MFCC_4',
 'AU04_mid_MFCC_5',
 'AU04_mid_MFCC_6',
 'AU04_mid_MFCC_7',
 'AU04_mid_MFCC_8',
 'AU04_mid_MFCC_9',
 'AU04_mid_Max',
 'AU04_mid_Max power spectrum',
 'AU04_mid_Maximum frequency',
 'AU04_mid_Mean',
 'AU04_mid_Mean absolute deviation',
 'AU04_mid_Mean absolute diff',
 'AU04_mid_Mean diff',
 'AU04_mid_Median',
 'AU04_mid_Median absolute deviation',
 'AU04_mid_Median absolute diff',
 'AU04_mid_Median diff',
 'AU04_mid_Median frequency',
 'AU04_mid_Min',
 'AU04_mid_Negative turning points',
 'AU04_mid_Neighbourhood peaks',
 'AU04_mid_Peak to peak distance',
 'AU04_mid_Positive turning points',
 'AU04_mid_Power bandwidth',
 'AU04_mid_Root mean square',
 'AU04_mid_Signal distance',
 'AU04_mid_Skewness',
 'AU04_mid_Slope',
 'AU04_mid_Spectral centroid',
 'AU04_mid_Spectral decrease',
 'AU04_mid_Spectral distance',
 'AU04_mid_Spectral entropy',
 'AU04_mid_Spectral kurtosis',
 'AU04_mid_Spectral positive turning points',
 'AU04_mid_Spectral roll-off',
 'AU04_mid_Spectral roll-on',
 'AU04_mid_Spectral skewness',
 'AU04_mid_Spectral slope',
 'AU04_mid_Spectral spread',
 'AU04_mid_Spectral variation',
 'AU04_mid_Standard deviation',
 'AU04_mid_Sum absolute diff',
 'AU04_mid_Variance',
 'AU04_mid_Wavelet absolute mean_12.5Hz',
 'AU04_mid_Wavelet absolute mean_2.78Hz',
 'AU04_mid_Wavelet absolute mean_25.0Hz',
 'AU04_mid_Wavelet absolute mean_3.12Hz',
 'AU04_mid_Wavelet absolute mean_3.57Hz',
 'AU04_mid_Wavelet absolute mean_4.17Hz',
 'AU04_mid_Wavelet absolute mean_5.0Hz',
 'AU04_mid_Wavelet absolute mean_6.25Hz',
 'AU04_mid_Wavelet absolute mean_8.33Hz',
 'AU04_mid_Wavelet energy_12.5Hz',
 'AU04_mid_Wavelet energy_2.78Hz',
 'AU04_mid_Wavelet energy_25.0Hz',
 'AU04_mid_Wavelet energy_3.12Hz',
 'AU04_mid_Wavelet energy_3.57Hz',
 'AU04_mid_Wavelet energy_4.17Hz',
 'AU04_mid_Wavelet energy_5.0Hz',
 'AU04_mid_Wavelet energy_6.25Hz',
 'AU04_mid_Wavelet energy_8.33Hz',
 'AU04_mid_Wavelet entropy',
 'AU04_mid_Wavelet standard deviation_12.5Hz',
 'AU04_mid_Wavelet standard deviation_2.78Hz',
 'AU04_mid_Wavelet standard deviation_25.0Hz',
 'AU04_mid_Wavelet standard deviation_3.12Hz',
 'AU04_mid_Wavelet standard deviation_3.57Hz',
 'AU04_mid_Wavelet standard deviation_4.17Hz',
 'AU04_mid_Wavelet standard deviation_5.0Hz',
 'AU04_mid_Wavelet standard deviation_6.25Hz',
 'AU04_mid_Wavelet standard deviation_8.33Hz',
 'AU04_mid_Wavelet variance_12.5Hz',
 'AU04_mid_Wavelet variance_2.78Hz',
 'AU04_mid_Wavelet variance_25.0Hz',
 'AU04_mid_Wavelet variance_3.12Hz',
 'AU04_mid_Wavelet variance_3.57Hz',
 'AU04_mid_Wavelet variance_4.17Hz',
 'AU04_mid_Wavelet variance_5.0Hz',
 'AU04_mid_Wavelet variance_6.25Hz',
 'AU04_mid_Wavelet variance_8.33Hz',
 'AU04_mid_Zero crossing rate',
 'AU06_mid_Absolute energy',
 'AU06_mid_Area under the curve',
 'AU06_mid_Autocorrelation',
 'AU06_mid_Average power',
 'AU06_mid_Centroid',
 'AU06_mid_ECDF Percentile Count_0',
 'AU06_mid_ECDF Percentile Count_1',
 'AU06_mid_ECDF Percentile_0',
 'AU06_mid_ECDF Percentile_1',
 'AU06_mid_ECDF_0',
 'AU06_mid_ECDF_1',
 'AU06_mid_ECDF_2',
 'AU06_mid_ECDF_3',
 'AU06_mid_ECDF_4',
 'AU06_mid_ECDF_5',
 'AU06_mid_ECDF_6',
 'AU06_mid_ECDF_7',
 'AU06_mid_ECDF_8',
 'AU06_mid_ECDF_9',
 'AU06_mid_Entropy',
 'AU06_mid_Fundamental frequency',
 'AU06_mid_Histogram mode',
 'AU06_mid_Human range energy',
 'AU06_mid_Interquartile range',
 'AU06_mid_Kurtosis',
 'AU06_mid_LPCC_0',
 'AU06_mid_LPCC_1',
 'AU06_mid_LPCC_10',
 'AU06_mid_LPCC_11',
 'AU06_mid_LPCC_2',
 'AU06_mid_LPCC_3',
 'AU06_mid_LPCC_4',
 'AU06_mid_LPCC_5',
 'AU06_mid_LPCC_6',
 'AU06_mid_LPCC_7',
 'AU06_mid_LPCC_8',
 'AU06_mid_LPCC_9',
 'AU06_mid_MFCC_0',
 'AU06_mid_MFCC_1',
 'AU06_mid_MFCC_10',
 'AU06_mid_MFCC_11',
 'AU06_mid_MFCC_2',
 'AU06_mid_MFCC_3',
 'AU06_mid_MFCC_4',
 'AU06_mid_MFCC_5',
 'AU06_mid_MFCC_6',
 'AU06_mid_MFCC_7',
 'AU06_mid_MFCC_8',
 'AU06_mid_MFCC_9',
 'AU06_mid_Max',
 'AU06_mid_Max power spectrum',
 'AU06_mid_Maximum frequency',
 'AU06_mid_Mean',
 'AU06_mid_Mean absolute deviation',
 'AU06_mid_Mean absolute diff',
 'AU06_mid_Mean diff',
 'AU06_mid_Median',
 'AU06_mid_Median absolute deviation',
 'AU06_mid_Median absolute diff',
 'AU06_mid_Median diff',
 'AU06_mid_Median frequency',
 'AU06_mid_Min',
 'AU06_mid_Negative turning points',
 'AU06_mid_Neighbourhood peaks',
 'AU06_mid_Peak to peak distance',
 'AU06_mid_Positive turning points',
 'AU06_mid_Power bandwidth',
 'AU06_mid_Root mean square',
 'AU06_mid_Signal distance',
 'AU06_mid_Skewness',
 'AU06_mid_Slope',
 'AU06_mid_Spectral centroid',
 'AU06_mid_Spectral decrease',
 'AU06_mid_Spectral distance',
 'AU06_mid_Spectral entropy',
 'AU06_mid_Spectral kurtosis',
 'AU06_mid_Spectral positive turning points',
 'AU06_mid_Spectral roll-off',
 'AU06_mid_Spectral roll-on',
 'AU06_mid_Spectral skewness',
 'AU06_mid_Spectral slope',
 'AU06_mid_Spectral spread',
 'AU06_mid_Spectral variation',
 'AU06_mid_Standard deviation',
 'AU06_mid_Sum absolute diff',
 'AU06_mid_Variance',
 'AU06_mid_Wavelet absolute mean_12.5Hz',
 'AU06_mid_Wavelet absolute mean_2.78Hz',
 'AU06_mid_Wavelet absolute mean_25.0Hz',
 'AU06_mid_Wavelet absolute mean_3.12Hz',
 'AU06_mid_Wavelet absolute mean_3.57Hz',
 'AU06_mid_Wavelet absolute mean_4.17Hz',
 'AU06_mid_Wavelet absolute mean_5.0Hz',
 'AU06_mid_Wavelet absolute mean_6.25Hz',
 'AU06_mid_Wavelet absolute mean_8.33Hz',
 'AU06_mid_Wavelet energy_12.5Hz',
 'AU06_mid_Wavelet energy_2.78Hz',
 'AU06_mid_Wavelet energy_25.0Hz',
 'AU06_mid_Wavelet energy_3.12Hz',
 'AU06_mid_Wavelet energy_3.57Hz',
 'AU06_mid_Wavelet energy_4.17Hz',
 'AU06_mid_Wavelet energy_5.0Hz',
 'AU06_mid_Wavelet energy_6.25Hz',
 'AU06_mid_Wavelet energy_8.33Hz',
 'AU06_mid_Wavelet entropy',
 'AU06_mid_Wavelet standard deviation_12.5Hz',
 'AU06_mid_Wavelet standard deviation_2.78Hz',
 'AU06_mid_Wavelet standard deviation_25.0Hz',
 'AU06_mid_Wavelet standard deviation_3.12Hz',
 'AU06_mid_Wavelet standard deviation_3.57Hz',
 'AU06_mid_Wavelet standard deviation_4.17Hz',
 'AU06_mid_Wavelet standard deviation_5.0Hz',
 'AU06_mid_Wavelet standard deviation_6.25Hz',
 'AU06_mid_Wavelet standard deviation_8.33Hz',
 'AU06_mid_Wavelet variance_12.5Hz',
 'AU06_mid_Wavelet variance_2.78Hz',
 'AU06_mid_Wavelet variance_25.0Hz',
 'AU06_mid_Wavelet variance_3.12Hz',
 'AU06_mid_Wavelet variance_3.57Hz',
 'AU06_mid_Wavelet variance_4.17Hz',
 'AU06_mid_Wavelet variance_5.0Hz',
 'AU06_mid_Wavelet variance_6.25Hz',
 'AU06_mid_Wavelet variance_8.33Hz',
 'AU06_mid_Zero crossing rate',
 'AU07_mid_Absolute energy',
 'AU07_mid_Area under the curve',
 'AU07_mid_Autocorrelation',
 'AU07_mid_Average power',
 'AU07_mid_Centroid',
 'AU07_mid_ECDF Percentile Count_0',
 'AU07_mid_ECDF Percentile Count_1',
 'AU07_mid_ECDF Percentile_0',
 'AU07_mid_ECDF Percentile_1',
 'AU07_mid_ECDF_0',
 'AU07_mid_ECDF_1',
 'AU07_mid_ECDF_2',
 'AU07_mid_ECDF_3',
 'AU07_mid_ECDF_4',
 'AU07_mid_ECDF_5',
 'AU07_mid_ECDF_6',
 'AU07_mid_ECDF_7',
 'AU07_mid_ECDF_8',
 'AU07_mid_ECDF_9',
 'AU07_mid_Entropy',
 'AU07_mid_Fundamental frequency',
 'AU07_mid_Histogram mode',
 'AU07_mid_Human range energy',
 'AU07_mid_Interquartile range',
 'AU07_mid_Kurtosis',
 'AU07_mid_LPCC_0',
 'AU07_mid_LPCC_1',
 'AU07_mid_LPCC_10',
 'AU07_mid_LPCC_11',
 'AU07_mid_LPCC_2',
 'AU07_mid_LPCC_3',
 'AU07_mid_LPCC_4',
 'AU07_mid_LPCC_5',
 'AU07_mid_LPCC_6',
 'AU07_mid_LPCC_7',
 'AU07_mid_LPCC_8',
 'AU07_mid_LPCC_9',
 'AU07_mid_MFCC_0',
 'AU07_mid_MFCC_1',
 'AU07_mid_MFCC_10',
 'AU07_mid_MFCC_11',
 'AU07_mid_MFCC_2',
 'AU07_mid_MFCC_3',
 'AU07_mid_MFCC_4',
 'AU07_mid_MFCC_5',
 'AU07_mid_MFCC_6',
 'AU07_mid_MFCC_7',
 'AU07_mid_MFCC_8',
 'AU07_mid_MFCC_9',
 'AU07_mid_Max',
 'AU07_mid_Max power spectrum',
 'AU07_mid_Maximum frequency',
 'AU07_mid_Mean',
 'AU07_mid_Mean absolute deviation',
 'AU07_mid_Mean absolute diff',
 'AU07_mid_Mean diff',
 'AU07_mid_Median',
 'AU07_mid_Median absolute deviation',
 'AU07_mid_Median absolute diff',
 'AU07_mid_Median diff',
 'AU07_mid_Median frequency',
 'AU07_mid_Min',
 'AU07_mid_Negative turning points',
 'AU07_mid_Neighbourhood peaks',
 'AU07_mid_Peak to peak distance',
 'AU07_mid_Positive turning points',
 'AU07_mid_Power bandwidth',
 'AU07_mid_Root mean square',
 'AU07_mid_Signal distance',
 'AU07_mid_Skewness',
 'AU07_mid_Slope',
 'AU07_mid_Spectral centroid',
 'AU07_mid_Spectral decrease',
 'AU07_mid_Spectral distance',
 'AU07_mid_Spectral entropy',
 'AU07_mid_Spectral kurtosis',
 'AU07_mid_Spectral positive turning points',
 'AU07_mid_Spectral roll-off',
 'AU07_mid_Spectral roll-on',
 'AU07_mid_Spectral skewness',
 'AU07_mid_Spectral slope',
 'AU07_mid_Spectral spread',
 'AU07_mid_Spectral variation',
 'AU07_mid_Standard deviation',
 'AU07_mid_Sum absolute diff',
 'AU07_mid_Variance',
 'AU07_mid_Wavelet absolute mean_12.5Hz',
 'AU07_mid_Wavelet absolute mean_2.78Hz',
 'AU07_mid_Wavelet absolute mean_25.0Hz',
 'AU07_mid_Wavelet absolute mean_3.12Hz',
 'AU07_mid_Wavelet absolute mean_3.57Hz',
 'AU07_mid_Wavelet absolute mean_4.17Hz',
 'AU07_mid_Wavelet absolute mean_5.0Hz',
 'AU07_mid_Wavelet absolute mean_6.25Hz',
 'AU07_mid_Wavelet absolute mean_8.33Hz',
 'AU07_mid_Wavelet energy_12.5Hz',
 'AU07_mid_Wavelet energy_2.78Hz',
 'AU07_mid_Wavelet energy_25.0Hz',
 'AU07_mid_Wavelet energy_3.12Hz',
 'AU07_mid_Wavelet energy_3.57Hz',
 'AU07_mid_Wavelet energy_4.17Hz',
 'AU07_mid_Wavelet energy_5.0Hz',
 'AU07_mid_Wavelet energy_6.25Hz',
 'AU07_mid_Wavelet energy_8.33Hz',
 'AU07_mid_Wavelet entropy',
 'AU07_mid_Wavelet standard deviation_12.5Hz',
 'AU07_mid_Wavelet standard deviation_2.78Hz',
 'AU07_mid_Wavelet standard deviation_25.0Hz',
 'AU07_mid_Wavelet standard deviation_3.12Hz',
 'AU07_mid_Wavelet standard deviation_3.57Hz',
 'AU07_mid_Wavelet standard deviation_4.17Hz',
 'AU07_mid_Wavelet standard deviation_5.0Hz',
 'AU07_mid_Wavelet standard deviation_6.25Hz',
 'AU07_mid_Wavelet standard deviation_8.33Hz',
 'AU07_mid_Wavelet variance_12.5Hz',
 'AU07_mid_Wavelet variance_2.78Hz',
 'AU07_mid_Wavelet variance_25.0Hz',
 'AU07_mid_Wavelet variance_3.12Hz',
 'AU07_mid_Wavelet variance_3.57Hz',
 'AU07_mid_Wavelet variance_4.17Hz',
 'AU07_mid_Wavelet variance_5.0Hz',
 'AU07_mid_Wavelet variance_6.25Hz',
 'AU07_mid_Wavelet variance_8.33Hz',
 'AU07_mid_Zero crossing rate',
 'AU10_mid_Absolute energy',
 'AU10_mid_Area under the curve',
 'AU10_mid_Autocorrelation',
 'AU10_mid_Average power',
 'AU10_mid_Centroid',
 'AU10_mid_ECDF Percentile Count_0',
 'AU10_mid_ECDF Percentile Count_1',
 'AU10_mid_ECDF Percentile_0',
 'AU10_mid_ECDF Percentile_1',
 'AU10_mid_ECDF_0',
 'AU10_mid_ECDF_1',
 'AU10_mid_ECDF_2',
 'AU10_mid_ECDF_3',
 'AU10_mid_ECDF_4',
 'AU10_mid_ECDF_5',
 'AU10_mid_ECDF_6',
 'AU10_mid_ECDF_7',
 'AU10_mid_ECDF_8',
 'AU10_mid_ECDF_9',
 'AU10_mid_Entropy',
 'AU10_mid_Fundamental frequency',
 'AU10_mid_Histogram mode',
 'AU10_mid_Human range energy',
 'AU10_mid_Interquartile range',
 'AU10_mid_Kurtosis',
 'AU10_mid_LPCC_0',
 'AU10_mid_LPCC_1',
 'AU10_mid_LPCC_10',
 'AU10_mid_LPCC_11',
 'AU10_mid_LPCC_2',
 'AU10_mid_LPCC_3',
 'AU10_mid_LPCC_4',
 'AU10_mid_LPCC_5',
 'AU10_mid_LPCC_6',
 'AU10_mid_LPCC_7',
 'AU10_mid_LPCC_8',
 'AU10_mid_LPCC_9',
 'AU10_mid_MFCC_0',
 'AU10_mid_MFCC_1',
 'AU10_mid_MFCC_10',
 'AU10_mid_MFCC_11',
 'AU10_mid_MFCC_2',
 'AU10_mid_MFCC_3',
 'AU10_mid_MFCC_4',
 'AU10_mid_MFCC_5',
 'AU10_mid_MFCC_6',
 'AU10_mid_MFCC_7',
 'AU10_mid_MFCC_8',
 'AU10_mid_MFCC_9',
 'AU10_mid_Max',
 'AU10_mid_Max power spectrum',
 'AU10_mid_Maximum frequency',
 'AU10_mid_Mean',
 'AU10_mid_Mean absolute deviation',
 'AU10_mid_Mean absolute diff',
 'AU10_mid_Mean diff',
 'AU10_mid_Median',

In [65]:
for feature in features:
    a = stats.pearsonr(data_AU_test[feature], y)[0]
    b = stats.pearsonr(data_AU_test[feature], y)[1]
    r_value.append(abs(a))
    p_value.append(b)
    mean_value_HC.append(np.mean(data_AU_HC[feature]))
    std_value_HC.append(np.std(data_AU_HC[feature]))
    mean_value_dep.append(np.mean(data_AU_dep[feature]))
    std_value_dep.append(np.std(data_AU_dep[feature]))

C:\Users\skiju\anaconda3\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))

In [66]:
statistical_AU = pd.DataFrame(columns=['name_column', '|r-value|', 'p-value', 'HC_mean', 'HC_std', 'dep_mean', 'dep_std'])

In [67]:
statistical_AU['name_column'] = features
statistical_AU['|r-value|'] = r_value
statistical_AU['p-value'] = p_value
statistical_AU['HC_mean'] = mean_value_HC
statistical_AU['HC_std'] = std_value_HC
statistical_AU['dep_mean'] = mean_value_dep
statistical_AU['dep_std'] = std_value_dep

In [71]:
statistical_AU.to_csv('.\dataset\statistical\stat_AU.csv')

# Statistical analysis Euler Angles

In [73]:
data_eul = pd.read_csv('euler_features.csv')

In [74]:
data_eul

,Unnamed: 0,level_0,index,patient,record,diagnosis,timestamp_start,timestamp_end,X_mid_Absolute energy,X_mid_Area under the curve,...,Z_eve_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1,Z_eve_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1,Z_eve_SP_Summaries_welch_rect_centroid,Z_eve_FC_LocalSimple_mean3_stderr,X_eve_app_ent,Y_eve_app_ent,Z_eve_app_ent,X_eve_rsd,Y_eve_rsd,Z_eve_rsd
0,0,0,0,P08,0,0,1.658354e+09,1.659996e+09,2.385522e+04,17.340800,...,0.183673,0.877551,0.038350,0.556470,1.240145,1.414059,1.101619,-137.406912,247.810229,-84.170855
1,1,1,0,P08,1,0,1.659996e+09,1.661206e+09,2.328345e+05,239.885354,...,0.437500,0.875000,0.104311,0.664134,1.110772,1.153594,1.206691,-246.703278,-917.852063,-147.429543
2,2,2,0,P10,2,1,1.658354e+09,1.659996e+09,4.725678e+04,54.145724,...,0.125000,0.854167,0.193282,0.768328,0.829204,1.076619,1.013430,114.967050,-107.494007,-224.427014
3,3,3,0,P10,3,0,1.659996e+09,1.662070e+09,1.807770e+05,129.773994,...,0.224490,0.122449,0.138058,0.682936,0.659745,0.789076,0.931019,65.528455,-348.921557,-328.457878
4,4,4,0,P12,4,1,1.658441e+09,1.659996e+09,4.557987e+04,24.120677,...,0.860465,0.139535,0.613592,0.924430,0.938069,0.806088,0.934574,72.352631,177.627123,159.713801
5,5,5,0,P12,5,1,1.659996e+09,1.661206e+09,2.937881e+04,14.343478,...,0.619048,0.738095,0.269981,0.758146,0.529294,0.502848,0.595768,44.882796,-1732.345347,174.352004
6,6,6,0,P13,6,0,1.658700e+09,1.659996e+09,1.425495e+05,166.412023,...,0.755102,0.510204,0.036816,0.527443,0.646985,0.687472,0.806980,172.224880,46.271562,73.328927
7,7,7,0,P13,7,0,1.659996e+09,1.661206e+09,1.526638e+04,15.338700,...,0.780488,0.731707,0.220893,0.714463,0.864127,0.889067,0.751850,-108.350642,22.814158,63.237315
8,8,8,0,P14,8,0,1.658700e+09,1.659910e+09,2.917384e+04,22.015482,...,0.448980,0.530612,0.085903,0.636002,1.382823,1.206934,1.187669,318.194246,-125.681839,133.769104
9,9,9,0,P15,9,0,1.658786e+09,1.660082e+09,NaN,NaN,...,0.122449,0.448980,0.171806,0.654882,0.913396,0.750667,0.753536,42.929179,1791.647415,1154.407059
10,10,10,0,P15,10,1,1.660082e+09,1.661206e+09,1.737008e+05,103.388069,...,0.204082,0.877551,0.233165,0.722889,0.745131,0.752576,0.874068,62.402568,12200.127526,283.902945
11,11,11,0,P16,11,0,1.658873e+09,1.659996e+09,2.302304e+06,1236.346278,...,0.220000,0.140000,0.095490,0.630106,0.716455,0.694768,0.883786,81.659767,-520.957701,73.706644
12,12,12,0,P16,12,0,1.659996e+09,1.661206e+09,1.302403e+06,728.651101,...,0.240000,0.820000,0.161068,0.712716,0.749267,0.881995,1.036046,90.985271,-879.392994,67.290676
13,13,13,0,P17,13,1,1.658786e+09,1.659996e+09,3.208747e+04,36.392223,...,0.270833,0.812500,0.291456,0.822146,1.004644,1.144014,1.295719,81.538374,686.473191,156.711907
14,14,14,0,P18,14,1,1.658873e+09,1.659996e+09,4.090342e+05,269.571245,...,0.163265,0.122449,0.116583,0.683514,1.348638,1.196337,1.133462,47.327685,-772.470353,258.826406
15,15,15,0,P18,15,1,1.659996e+09,1.661206e+09,4.377093e+05,257.597133,...,0.367347,0.714286,0.148796,0.712698,1.257952,0.979177,1.103751,63.622003,-341.175758,-1184.535555
16,16,16,0,P19,16,1,1.658873e+09,1.660255e+09,1.946176e+04,37.826394,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
17,17,17,0,P19,17,1,1.660255e+09,1.661897e+09,1.271333e+04,26.636822,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
18,18,18,0,P20,18,0,1.658786e+09,1.660082e+09,1.774296e+05,102.492349,...,0.375000,0.875000,0.092039,0.651827,0.808821,0.759898,0.924682,77.662710,-521.668527,-500.317074
19,19,19,0,P20,19,0,1.660082e+09,1.661810e+09,1.428093e+05,79.795842,...,0.765957,0.765957,0.306796,0.831599,0.883499,0.802121,0.904028,43.516442,-152.723374,-609.727436
20,20,20,0,P21,20,0,1.658959e+09,1.660169e+09,8.525104e+04,96.856466,...,0.857143,0.734694,0.033748,0.483177,0.823738,0.732468,0.599353,236.903653,-731.602823,-236.548434
21,21,21,0,P21,21,1,1.660169e+09,1.661810e+09,2.998148e+04,38.033857,...,0.142857,0.122449,0.018408,0.423411,0.976725,0.927626,0.592826,166.822358,-272.059310,378.801917
22,22,22,0,P23,22,0,1.659046e+09,1.660255e+09,2.071118e+05,124.147355,...,0.142857,0.122449,0.165670,0.779446,0.684134,0.684993,0.721743,91.361271,227.860434,137.081212
23,23,23,0,P23,23,0,1.660255e+09,1.661810e+09,4.935869e+05,261.020003,...,0.142857,0.224490,0.154932,0.638348,0.839413,0.611069,0.759300,68.424529,414.442518,178.512029
24,24,24,0,P24,24,1,1.659046e+09,1.660428e+09,2.794095e+05,329.216794,...,0.360000,0.620000,0.074398,0.574362,1.254626,1.188718,1.165499,160.889891,215.793478,1356.962550
25,25,25,0,P24,25,1,1.660428e+09,1.661810e+09,6.920620e+04,104.340501,...,0.244898,0.183673,0.090505,0.584386,1.299245,1.307400,1.107756,157.945336,126.015444,246.620638
26,26,26,0,P25,26,0,1.660774e+09,1.661983e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
27,27,27,0,P27,27,0,1.660514e+09,1.661724e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
28,28,28,0,P28,28,0,1.660514e+09,1.663279e+09,4.192882e+04,52.765973,...,0.326531,0.795918,0.078233,0.525366,0.796606,0.828557,0.822693,118.516619,-826.924369,135.896976
29,29,29,0,P29,29,0,1.659305e+09,1.660255e+09,6.656350e+05,522.587999,...,0.387755,0.530612,0.073631,0.566284,1.024214,0.609471,0.911550,30.481007,739.618210,151.253866
30,30,30,0,P29,30,0,1.660255e+09,1.661810e+09,8.155723e+05,618.118330,...,0.142857,0.836735,0.044485,0.591347,0.862309,0.730197,0.857840,33.571947,-1370.466385,-2691.185081
31,31,31,0,P30,31,1,1.659305e+09,1.660255e+09,1.648135e+06,799.078291,...,0.306122,0.714286,0.134223,0.706227,1.012830,1.181778,1.192320,101.949414,-387.438819,-359.940743
32,32,32,0,P30,32,1,1.660255e+09,1.661810e+09,1.416431e+06,673.771219,...,0.346939,0.510204,0.125019,0.675214,1.089338,1.128268,1.274522,92.760183,-520.650958,-291.697824
33,33,33,0,P31,33,0,1.659391e+09,1.660601e+09,8.374565e+05,341.777817,...,0.142857,0.877551,0.016874,0.386287,0.786770,0.543841,0.297664,23.406838,384.541061,705.739276
34,34,34,0,P31,34,0,1.660601e+09,1.661810e+09,5.963323e+05,245.186974,...,0.872340,0.851064,0.067495,0.456107,0.752665,0.656863,0.457564,27.380116,-810.587563,-62.962912
35,35,35,0,P33,35,0,1.659478e+09,1.660601e+09,1.240011e+05,138.264214,...,0.673469,0.714286,0.014573,0.363809,0.788975,0.760841,0.556171,-257.206934,-104.646432,11214.786426
36,36,36,0,P33,36,0,1.660601e+09,1.662070e+09,8.216622e+04,120.025222,...,0.673469,0.632653,0.030680,0.402100,0.870246,0.754503,0.500728,-302.284049,-69.070960,328.900087
37,37,37,0,P34,37,0,1.659564e+09,1.660774e+09,2.167278e+05,144.547551,...,0.125000,0.750000,0.193282,0.733465,0.970049,0.605108,0.908089,35.684895,6700.653138,276.467772
38,38,38,0,P35,38,0,1.659564e+09,1.660774e+09,1.303872e+05,112.606316,...,0.775510,0.591837,0.225495,0.771283,1.028943,0.941293,1.140582,79.495705,122.183045,499.331583
39,39,39,0,P35,39,0,1.660774e+09,1.662070e+09,3.243721e+05,220.622951,...,0.244898,0.653061,0.156466,0.673304,0.944400,0.977701,1.023298,75.766267,115.203053,227.014058
40,40,40,0,P36,40,0,1.660860e+09,1.662070e+09,2.573372e+05,220.269186,...,0.163265,0.142857,0.202485,0.763000,1.164823,1.035039,1.242862,124.295620,-135.939454,-185.267916
41,41,41,0,P38,41,0,1.659564e+09,1.661206e+09,4.329576e+05,247.863471,...,0.326531,0.775510,0.029146,0.410367,0.598555,0.821194,0.736928,75.920045,-189.245762,-1504.488006
42,42,42,0,P38,42,0,1.661206e+09,1.661983e+09,1.642575e+05,102.116400,...,0.250000,0.125000,0.009204,0.419243,0.689716,0.521414,0.552463,44.144951,-127.073653,-97.309417

In [75]:
del data_eul['Unnamed: 0']
del data_eul['index']
del data_eul['record']
del data_eul['level_0']

In [76]:
data_eul

,patient,diagnosis,timestamp_start,timestamp_end,X_mid_Absolute energy,X_mid_Area under the curve,X_mid_Autocorrelation,X_mid_Average power,X_mid_Centroid,X_mid_ECDF Percentile Count_0,...,Z_eve_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1,Z_eve_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1,Z_eve_SP_Summaries_welch_rect_centroid,Z_eve_FC_LocalSimple_mean3_stderr,X_eve_app_ent,Y_eve_app_ent,Z_eve_app_ent,X_eve_rsd,Y_eve_rsd,Z_eve_rsd
0,P08,0,1.658354e+09,1.659996e+09,2.385522e+04,17.340800,16.0,11580.203963,0.936651,41.0,...,0.183673,0.877551,0.038350,0.556470,1.240145,1.414059,1.101619,-137.406912,247.810229,-84.170855
1,P08,0,1.659996e+09,1.661206e+09,2.328345e+05,239.885354,42.0,6007.081693,21.592224,775.0,...,0.437500,0.875000,0.104311,0.664134,1.110772,1.153594,1.206691,-246.703278,-917.852063,-147.429543
2,P10,1,1.658354e+09,1.659996e+09,4.725678e+04,54.145724,63.0,4535.199168,6.523586,208.0,...,0.125000,0.854167,0.193282,0.768328,0.829204,1.076619,1.013430,114.967050,-107.494007,-224.427014
3,P10,0,1.659996e+09,1.662070e+09,1.807770e+05,129.773994,65.0,14002.863964,7.335980,258.0,...,0.224490,0.122449,0.138058,0.682936,0.659745,0.789076,0.931019,65.528455,-348.921557,-328.457878
4,P12,1,1.658441e+09,1.659996e+09,4.557987e+04,24.120677,8.0,30386.579672,0.962864,30.0,...,0.860465,0.139535,0.613592,0.924430,0.938069,0.806088,0.934574,72.352631,177.627123,159.713801
5,P12,1,1.659996e+09,1.661206e+09,2.937881e+04,14.343478,2.0,34974.776061,0.392917,17.0,...,0.619048,0.738095,0.269981,0.758146,0.529294,0.502848,0.595768,44.882796,-1732.345347,174.352004
6,P13,0,1.658700e+09,1.659996e+09,1.425495e+05,166.412023,56.0,4206.240544,18.322024,678.0,...,0.755102,0.510204,0.036816,0.527443,0.646985,0.687472,0.806980,172.224880,46.271562,73.328927
7,P13,0,1.659996e+09,1.661206e+09,1.526638e+04,15.338700,11.0,6131.074397,0.533629,50.0,...,0.780488,0.731707,0.220893,0.714463,0.864127,0.889067,0.751850,-108.350642,22.814158,63.237315
8,P14,0,1.658700e+09,1.659910e+09,2.917384e+04,22.015482,8.0,15354.652608,1.082417,38.0,...,0.448980,0.530612,0.085903,0.636002,1.382823,1.206934,1.187669,318.194246,-125.681839,133.769104
9,P15,0,1.658786e+09,1.660082e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,0.122449,0.448980,0.171806,0.654882,0.913396,0.750667,0.753536,42.929179,1791.647415,1154.407059
10,P15,1,1.660082e+09,1.661206e+09,1.737008e+05,103.388069,11.0,25657.434938,3.140234,135.0,...,0.204082,0.877551,0.233165,0.722889,0.745131,0.752576,0.874068,62.402568,12200.127526,283.902945
11,P16,0,1.658873e+09,1.659996e+09,2.302304e+06,1236.346278,51.0,27516.483424,45.273118,1673.0,...,0.220000,0.140000,0.095490,0.630106,0.716455,0.694768,0.883786,81.659767,-520.957701,73.706644
12,P16,0,1.659996e+09,1.661206e+09,1.302403e+06,728.651101,38.0,17002.649361,35.965444,1532.0,...,0.240000,0.820000,0.161068,0.712716,0.749267,0.881995,1.036046,90.985271,-879.392994,67.290676
13,P17,1,1.658786e+09,1.659996e+09,3.208747e+04,36.392223,34.0,4782.037941,3.885111,134.0,...,0.270833,0.812500,0.291456,0.822146,1.004644,1.144014,1.295719,81.538374,686.473191,156.711907
14,P18,1,1.658873e+09,1.659996e+09,4.090342e+05,269.571245,10.0,17768.642943,11.898989,460.0,...,0.163265,0.122449,0.116583,0.683514,1.348638,1.196337,1.133462,47.327685,-772.470353,258.826406
15,P18,1,1.659996e+09,1.661206e+09,4.377093e+05,257.597133,28.0,22608.949559,10.502108,387.0,...,0.367347,0.714286,0.148796,0.712698,1.257952,0.979177,1.103751,63.622003,-341.175758,-1184.535555
16,P19,1,1.658873e+09,1.660255e+09,1.946176e+04,37.826394,46.0,1291.424058,5.671386,301.0,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
17,P19,1,1.660255e+09,1.661897e+09,1.271333e+04,26.636822,42.0,1361.170554,3.956658,187.0,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
18,P20,0,1.658786e+09,1.660082e+09,1.774296e+05,102.492349,39.0,20800.662151,3.095727,170.0,...,0.375000,0.875000,0.092039,0.651827,0.808821,0.759898,0.924682,77.662710,-521.668527,-500.317074
19,P20,0,1.660082e+09,1.661810e+09,1.428093e+05,79.795842,18.0,19616.668229,3.687198,145.0,...,0.765957,0.765957,0.306796,0.831599,0.883499,0.802121,0.904028,43.516442,-152.723374,-609.727436
20,P21,0,1.658959e+09,1.660169e+09,8.525104e+04,96.856466,26.0,4239.236206,8.281299,402.0,...,0.857143,0.734694,0.033748,0.483177,0.823738,0.732468,0.599353,236.903653,-731.602823,-236.548434
21,P21,1,1.660169e+09,1.661810e+09,2.998148e+04,38.033857,17.0,3490.277533,3.654378,172.0,...,0.142857,0.122449,0.018408,0.423411,0.976725,0.927626,0.592826,166.822358,-272.059310,378.801917
22,P23,0,1.659046e+09,1.660255e+09,2.071118e+05,124.147355,41.0,11957.954140,13.895433,346.0,...,0.142857,0.122449,0.165670,0.779446,0.684134,0.684993,0.721743,91.361271,227.860434,137.081212
23,P23,0,1.660255e+09,1.661810e+09,4.935869e+05,261.020003,43.0,21937.196088,14.115106,450.0,...,0.142857,0.224490,0.154932,0.638348,0.839413,0.611069,0.759300,68.424529,414.442518,178.512029
24,P24,1,1.659046e+09,1.660428e+09,2.794095e+05,329.216794,65.0,3640.514209,35.806481,1535.0,...,0.360000,0.620000,0.074398,0.574362,1.254626,1.188718,1.165499,160.889891,215.793478,1356.962550
25,P24,1,1.660428e+09,1.661810e+09,6.920620e+04,104.340501,19.0,2275.023136,14.626497,608.0,...,0.244898,0.183673,0.090505,0.584386,1.299245,1.307400,1.107756,157.945336,126.015444,246.620638
26,P25,0,1.660774e+09,1.661983e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
27,P27,0,1.660514e+09,1.661724e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
28,P28,0,1.660514e+09,1.663279e+09,4.192882e+04,52.765973,48.0,3565.375641,5.577221,235.0,...,0.326531,0.795918,0.078233,0.525366,0.796606,0.828557,0.822693,118.516619,-826.924369,135.896976
29,P29,0,1.659305e+09,1.660255e+09,6.656350e+05,522.587999,44.0,13254.381399,22.455095,1004.0,...,0.387755,0.530612,0.073631,0.566284,1.024214,0.609471,0.911550,30.481007,739.618210,151.253866
30,P29,0,1.660255e+09,1.661810e+09,8.155723e+05,618.118330,138.0,16370.379979,23.657539,996.0,...,0.142857,0.836735,0.044485,0.591347,0.862309,0.730197,0.857840,33.571947,-1370.466385,-2691.185081
31,P30,1,1.659305e+09,1.660255e+09,1.648135e+06,799.078291,31.0,26833.845857,31.267339,1228.0,...,0.306122,0.714286,0.134223,0.706227,1.012830,1.181778,1.192320,101.949414,-387.438819,-359.940743
32,P30,1,1.660255e+09,1.661810e+09,1.416431e+06,673.771219,33.0,29301.436202,23.672326,967.0,...,0.346939,0.510204,0.125019,0.675214,1.089338,1.128268,1.274522,92.760183,-520.650958,-291.697824
33,P31,0,1.659391e+09,1.660601e+09,8.374565e+05,341.777817,7.0,59100.670379,6.933817,283.0,...,0.142857,0.877551,0.016874,0.386287,0.786770,0.543841,0.297664,23.406838,384.541061,705.739276
34,P31,0,1.660601e+09,1.661810e+09,5.963323e+05,245.186974,30.0,57229.588036,4.771805,208.0,...,0.872340,0.851064,0.067495,0.456107,0.752665,0.656863,0.457564,27.380116,-810.587563,-62.962912
35,P33,0,1.659478e+09,1.660601e+09,1.240011e+05,138.264214,59.0,4975.968115,11.862588,498.0,...,0.673469,0.714286,0.014573,0.363809,0.788975,0.760841,0.556171,-257.206934,-104.646432,11214.786426
36,P33,0,1.660601e+09,1.662070e+09,8.216622e+04,120.025222,19.0,3341.448433,12.320009,492.0,...,0.673469,0.632653,0.030680,0.402100,0.870246,0.754503,0.500728,-302.284049,-69.070960,328.900087
37,P34,0,1.659564e+09,1.660774e+09,2.167278e+05,144.547551,31.0,19350.694698,5.309470,224.0,...,0.125000,0.750000,0.193282,0.733465,0.970049,0.605108,0.908089,35.684895,6700.653138,276.467772
38,P35,0,1.659564e+09,1.660774e+09,1.303872e+05,112.606316,23.0,6208.912115,11.166546,420.0,...,0.775510,0.591837,0.225495,0.771283,1.028943,0.941293,1.140582,79.495705,122.183045,499.331583
39,P35,0,1.660774e+09,1.662070e+09,3.243721e+05,220.622951,18.0,12499.886626,12.452717,519.0,...,0.244898,0.653061,0.156466,0.673304,0.944400,0.977701,1.023298,75.766267,115.203053,227.014058
40,P36,0,1.660860e+09,1.662070e+09,2.573372e+05,220.269186,17.0,7627.067261,21.104571,675.0,...,0.163265,0.142857,0.202485,0.763000,1.164823,1.035039,1.242862,124.295620,-135.939454,-185.267916
41,P38,0,1.659564e+09,1.661206e+09,4.329576e+05,247.863471,61.0,21529.469314,11.592990,402.0,...,0.326531,0.775510,0.029146,0.410367,0.598555,0.821194,0.736928,75.920045,-189.245762,-1504.488006
42,P38,0,1.661206e+09,1.661983e+09,1.642575e+05,102.116400,18.0,23736.638028,3.387446,138.0,...,0.250000,0.125000,0.009204,0.419243,0.689716,0.521414,0.552463,44.144951,-127.073653,-97.309417

In [77]:
del data_eul['patient']
del data_eul['timestamp_start']
del data_eul['timestamp_end']

In [79]:
data_eul = data_eul.fillna(data_eul.mean())

In [80]:
data_eul_HC = data_eul[data_eul['diagnosis']==0]
data_eul_dep = data_eul[data_eul['diagnosis']==1]

In [81]:
del data_eul_HC['diagnosis']
del data_eul_dep['diagnosis']

In [82]:
data_eul_test = data_eul
y = data_eul['diagnosis']
del data_eul_test['diagnosis']

In [83]:
r_value = []
p_value = []
mean_value_HC = []
std_value_HC = []
mean_value_dep = []
std_value_dep = []

In [84]:
features = list(data_eul_test.columns)

In [86]:
for feature in features:
    a = stats.pearsonr(data_eul_test[feature], y)[0]
    b = stats.pearsonr(data_eul_test[feature], y)[1]
    r_value.append(abs(a))
    p_value.append(b)
    mean_value_HC.append(np.mean(data_eul_HC[feature]))
    std_value_HC.append(np.std(data_eul_HC[feature]))
    mean_value_dep.append(np.mean(data_eul_dep[feature]))
    std_value_dep.append(np.std(data_eul_dep[feature]))

In [87]:
statistical_eul = pd.DataFrame(columns=['name_column', '|r-value|', 'p-value', 'HC_mean', 'HC_std', 'dep_mean', 'dep_std'])

In [88]:
statistical_eul['name_column'] = features
statistical_eul['|r-value|'] = r_value
statistical_eul['p-value'] = p_value
statistical_eul['HC_mean'] = mean_value_HC
statistical_eul['HC_std'] = std_value_HC
statistical_eul['dep_mean'] = mean_value_dep
statistical_eul['dep_std'] = std_value_dep

In [89]:
statistical_eul.to_csv('.\dataset\statistical\stat_eul.csv')

# Eye-opening and smiling probabilities

In [93]:
data_prob = pd.read_csv('prob_eye_features.csv')

In [95]:
del data_prob['Unnamed: 0']
del data_prob['index']
del data_prob['record']

In [96]:
del data_prob['patient']
del data_prob['timestamp_start']
del data_prob['timestamp_end']

In [97]:
data_prob = data_prob.fillna(data_prob.mean())

In [98]:
data_prob_HC = data_prob[data_prob['diagnosis']==0]
data_prob_dep = data_prob[data_prob['diagnosis']==1]

In [99]:
del data_prob_HC['diagnosis']
del data_prob_dep['diagnosis']

In [100]:
data_prob_test = data_prob
y = data_prob['diagnosis']
del data_prob_test['diagnosis']

In [101]:
r_value = []
p_value = []
mean_value_HC = []
std_value_HC = []
mean_value_dep = []
std_value_dep = []

In [102]:
features = list(data_prob_test.columns)

In [103]:
for feature in features:
    a = stats.pearsonr(data_prob_test[feature], y)[0]
    b = stats.pearsonr(data_prob_test[feature], y)[1]
    r_value.append(abs(a))
    p_value.append(b)
    mean_value_HC.append(np.mean(data_prob_HC[feature]))
    std_value_HC.append(np.std(data_prob_HC[feature]))
    mean_value_dep.append(np.mean(data_prob_dep[feature]))
    std_value_dep.append(np.std(data_prob_dep[feature]))

C:\Users\skiju\anaconda3\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))

In [104]:
statistical_prob = pd.DataFrame(columns=['name_column', '|r-value|', 'p-value', 'HC_mean', 'HC_std', 'dep_mean', 'dep_std'])

In [105]:
statistical_prob['name_column'] = features
statistical_prob['|r-value|'] = r_value
statistical_prob['p-value'] = p_value
statistical_prob['HC_mean'] = mean_value_HC
statistical_prob['HC_std'] = std_value_HC
statistical_prob['dep_mean'] = mean_value_dep
statistical_prob['dep_std'] = std_value_dep

In [106]:
statistical_prob.to_csv('.\dataset\statistical\stat_prob.csv')

# Facial features

In [107]:
important_features = list(pd.read_csv('.\dataset\important_features.csv', header=None)[0])

In [108]:
import polars as pl
import csv

In [109]:
file_path = './dataset/ff/data_all_ff.csv'

In [111]:
#Use scan_csv and select to read specific columns
df = pl.scan_csv(file_path).select(important_features).collect()

In [112]:
columns_to_fill = list(df.columns[:-3])

In [113]:
df_filled = df.with_columns(
    [pl.when(pl.col(col).is_infinite()).then(None).otherwise(pl.col(col)).alias(col) for col in columns_to_fill]
    
)

In [114]:


# Fill NaN values with the mean for the specified columns
df_filled = df_filled.with_columns(
    [pl.col(col).fill_nan(pl.col(col).mean()) for col in columns_to_fill]
)

print(df_filled)

shape: (43, 14_663)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬────────┬─────────┐
│ 0_13distan ┆ 0_104angle ┆ 0_104angle ┆ 0_101angle ┆ … ┆ 93_103ang ┆ diagnosis ┆ record ┆ patient │
│ ce_mid_Hum ┆ _mid_MFCC_ ┆ _mid_Max   ┆ _mid_Spect ┆   ┆ le_eve_rs ┆ ---       ┆ ---    ┆ ---     │
│ an range   ┆ 5          ┆ ---        ┆ ral        ┆   ┆ d         ┆ i64       ┆ i64    ┆ str     │
│ e…         ┆ ---        ┆ f64        ┆ kurtos…    ┆   ┆ ---       ┆           ┆        ┆         │
│ ---        ┆ f64        ┆            ┆ ---        ┆   ┆ f64       ┆           ┆        ┆         │
│ f64        ┆            ┆            ┆ f64        ┆   ┆           ┆           ┆        ┆         │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪════════╪═════════╡
│ 0.00325    ┆ -1.840351  ┆ 1.568902   ┆ 2.212502   ┆ … ┆ -107.0520 ┆ 0         ┆ 0      ┆ P08     │
│            ┆            ┆            ┆            ┆   ┆ 95        ┆           ┆        ┆         │
│ 0.000955   ┆ 10.081815  ┆ 1.570796   ┆ 1.89806    ┆ … ┆ -325.9672 ┆ 0         ┆ 1      ┆ P08     │
│            ┆            ┆            ┆            ┆   ┆ 88        ┆           ┆        ┆         │
│ 0.00011    ┆ 69.328889  ┆ 1.570796   ┆ 2.235668   ┆ … ┆ 62.15462  ┆ 1         ┆ 2      ┆ P10     │
│ 0.000263   ┆ 78.030851  ┆ 1.570796   ┆ 2.323626   ┆ … ┆ 137.13035 ┆ 0         ┆ 3      ┆ P10     │
│            ┆            ┆            ┆            ┆   ┆ 5         ┆           ┆        ┆         │
│ 0.000042   ┆ -27.148089 ┆ 1.570796   ┆ 1.861678   ┆ … ┆ 295.45099 ┆ 1         ┆ 4      ┆ P12     │
│            ┆            ┆            ┆            ┆   ┆ 4         ┆           ┆        ┆         │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …      ┆ …       │
│ 0.000184   ┆ 35.690312  ┆ 1.570796   ┆ 1.999382   ┆ … ┆ -178.4325 ┆ 0         ┆ 38     ┆ P35     │
│            ┆            ┆            ┆            ┆   ┆ 8         ┆           ┆        ┆         │
│ 0.003416   ┆ 10.500244  ┆ 1.570796   ┆ 2.004796   ┆ … ┆ -216.9368 ┆ 0         ┆ 39     ┆ P35     │
│            ┆            ┆            ┆            ┆   ┆ 01        ┆           ┆        ┆         │
│ 0.001496   ┆ -1.27798   ┆ 1.570796   ┆ 2.182357   ┆ … ┆ 249.47283 ┆ 0         ┆ 40     ┆ P36     │
│ 0.000854   ┆ 22.403886  ┆ 1.570796   ┆ 2.387518   ┆ … ┆ 477.62064 ┆ 0         ┆ 41     ┆ P38     │
│            ┆            ┆            ┆            ┆   ┆ 4         ┆           ┆        ┆         │
│ 0.000057   ┆ 50.383792  ┆ 1.570796   ┆ 5.353932   ┆ … ┆ -664.9511 ┆ 0         ┆ 42     ┆ P38     │
│            ┆            ┆            ┆            ┆   ┆ 97        ┆           ┆        ┆         │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴────────┴─────────┘

In [115]:
df_filled2 = df_filled.with_columns(
    [pl.col(col).fill_null(pl.col(col).mean()) for col in columns_to_fill]
)

In [116]:
X = df_filled2[df_filled2.columns[:-3]]

In [117]:
X = X.to_pandas()

In [118]:
group = df_filled2['patient'].to_pandas()

In [119]:
groups = group

In [120]:
y = df_filled2['diagnosis'].to_pandas()

In [121]:
records  = df_filled2['record'].to_pandas()

In [124]:
data_ff = pd.concat([y, X], axis=1)

,diagnosis,0_13distance_mid_Human range energy,0_104angle_mid_MFCC_5,0_104angle_mid_Max,0_101angle_mid_Spectral kurtosis,0_16distance_mid_ECDF_0,0_127angle_mid_Spectral decrease,0_107angle_mid_Max power spectrum,0_122distance_mid_Median diff,0_123angle_mid_MFCC_1,...,55_105angle_eve_rsd,44_54angle_eve_rsd,70_82distance_eve_rsd,43_51angle_eve_rsd,109_117angle_eve_rsd,59_69angle_eve_rsd,110_111angle_eve_rsd,64_124angle_eve_rsd,106_109angle_eve_rsd,93_103angle_eve_rsd
0,0,0.003250,-1.840351,1.568902,2.212502,0.004831,-1.079578,0.545417,-0.010843,-68.433294,...,-51.343138,67.763495,1.382429,52.873894,46.697858,202.789080,1383.660106,-58.588626,178.580409,-107.052095
1,0,0.000955,10.081815,1.570796,1.898060,0.000258,-0.272252,5.245545,0.001702,-24.671142,...,-106.718558,114.804993,1.675652,72.912386,55.323645,197.969723,-495.127710,-110.520797,144.754258,-325.967288
2,1,0.000110,69.328889,1.570796,2.235668,0.001130,-0.785619,0.147481,-0.000486,-22.544975,...,-145.589786,645.392595,1.021050,44.300970,26.021285,164.124128,11587.365133,-101.816203,26.929642,62.154620
3,0,0.000263,78.030851,1.570796,2.323626,0.000897,-0.259407,0.051975,0.001393,-20.399725,...,-284.593329,912.118427,1.199724,46.470249,30.388807,-525.380688,196.086475,-119.914317,36.841969,137.130355
4,1,0.000042,-27.148089,1.570796,1.861678,0.006623,-0.767740,0.023533,0.002480,-8.105020,...,310.271316,-282.929401,1.952581,287.355117,61.243625,1082.071061,-857.901089,434.934293,67.797981,295.450994
5,1,0.000469,14.970590,1.568357,2.026775,0.011765,-1.149265,0.030957,-0.000262,-86.000882,...,147.260741,-155.883294,1.473812,427.659922,64.214727,514.732773,-395.997262,161.851396,70.235880,117.903253
6,0,0.000350,40.421336,1.568454,2.085611,0.000295,-1.375563,0.713760,0.001193,-21.588570,...,55.500204,-214.075757,1.297797,107.747378,36.554223,78.725785,-103.424195,68.516986,29.666199,-173.979804
7,0,0.000108,28.664611,1.570796,3.358030,0.004000,-0.592514,0.703830,-0.001916,-31.573657,...,88.526928,-2562.948886,0.977047,53.012193,22.533279,4.457467,-32.598258,42.621967,15.453300,-139.264115
8,0,0.000198,12.507607,1.553527,1.742731,0.005236,-0.190092,0.008482,0.002279,-17.564342,...,128.583960,-90.187301,1.850571,-511.598888,88.994644,69.059974,-81.258403,272.404397,92.216660,65.162159
9,0,0.000918,32.330542,1.570056,2.210358,0.001453,-0.331715,1.032832,0.000133,-18.094546,...,-388.031551,1536.097858,1.193838,62.420082,44.912848,-108.463034,719.874536,-221.930210,33.245194,278.504680
10,1,0.000103,43.878287,1.570796,1.890539,0.001475,0.039249,0.168138,-0.003022,41.400024,...,1831.271706,-635.463104,1.198536,82.951255,68.859277,-220.491901,-407.445033,-706.703815,43.775909,179.313971
11,0,0.000635,-2.542777,1.570796,2.039158,0.000120,-0.499154,0.609854,-0.000071,-31.061592,...,87.538777,-61.632303,1.461063,-547.301258,44.255461,98.885516,-145.854092,70.131374,51.976531,43.210460
12,0,0.001152,33.390197,1.570796,2.031939,0.000131,-0.549643,0.444095,0.000139,-20.676983,...,84.304673,-62.229541,1.448992,-516.631625,42.758889,112.905458,-150.929346,71.600240,62.795920,60.604857
13,1,0.000664,5.911047,1.570796,1.875352,0.001488,-0.885154,0.073821,0.004805,-10.005949,...,106.836169,-167.264637,1.279774,78.763820,44.247202,551.632478,-240.746832,537.408796,83.234786,116.641351
14,1,0.000366,11.895525,1.570796,1.994754,0.000434,-0.007087,0.550548,0.000452,-11.881407,...,160.922400,-247.942251,1.545944,128.611769,52.125001,263.430746,-247.485433,-311.154789,48.211933,162.902524
15,1,0.000330,68.620585,1.570796,2.017342,0.000516,-0.028217,0.420468,0.002894,-13.596448,...,5609.199027,2014.403445,1.624990,102.975433,53.514319,2926.249266,-1263.689062,-173.008747,89.600324,304.191197
16,1,0.000625,85.292462,1.570796,2.050188,0.000663,-0.461059,0.105330,-0.002881,-55.816097,...,1425.655666,-17506.822776,1.366718,119.729855,44.019813,263.426432,256.445680,528.490892,71.131364,-91.624224
17,1,0.000096,20.500762,1.570796,2.273583,0.001070,-0.056102,2.058002,0.002281,-27.939950,...,1425.655666,-17506.822776,1.366718,119.729855,44.019813,263.426432,256.445680,528.490892,71.131364,-91.624224
18,0,0.000496,31.713142,1.570796,1.872098,0.001171,-0.090991,0.241916,0.002967,8.991695,...,-6746.826209,11208.159325,1.265733,116.513038,47.613284,470.393155,614.494611,-198.415077,87.448664,571.805748
19,0,0.000351,33.035458,1.569566,1.988514,0.001372,-0.041991,0.123599,0.004312,-74.649297,...,-3775.417565,-754.990697,1.254518,78.725724,24.944324,-431.625933,188.212879,-64.096889,199.909257,148.039686
20,0,0.000695,32.057832,1.570796,2.217516,0.000641,-0.078946,0.428290,0.000886,-38.854733,...,-178.007908,245.356213,1.252452,95.104784,42.886665,166.124997,423.182550,-242.490545,37.233776,-9085.154582
21,1,0.001343,57.300812,1.570796,2.189624,0.001116,0.067534,1.832134,0.002715,-12.011291,...,1728.262862,-418.494548,1.516818,372.945930,61.818598,104.643947,-304.570168,862.716347,95.793470,183.707278
22,0,0.000479,3.963489,1.569149,2.316727,0.000651,-0.715170,0.613472,0.000425,-38.578647,...,110.437956,-259.051034,1.158488,95.827418,28.604044,76.959306,-110.231351,148.422178,53.328854,141.797967
23,0,0.000618,3.530664,1.570796,2.116602,0.000690,-0.274150,0.107282,0.000000,-2.598406,...,173.186111,2420.824091,1.509903,79.981497,29.334551,119.074983,-2514.150139,199.671341,54.976820,159.558714
24,1,0.000981,46.242835,1.570796,2.053867,0.000130,-0.044593,6.771509,0.000049,-14.216041,...,-789.422373,-698529.141138,1.769173,104.401020,63.350257,60.874336,-158.733030,587.793990,69.633789,571.558737
25,1,0.000524,26.574942,1.570796,2.291153,0.000532,-0.886195,1.357395,0.000889,67.123972,...,-1363.939388,-3379.303932,1.526995,115.032978,70.007449,91.072710,-152.984199,329.932709,71.504437,576.535342
26,0,0.000154,65.214874,1.567250,2.342385,0.002475,-0.288906,0.116745,-0.005028,-18.504180,...,1425.655666,-17506.822776,1.366718,119.729855,44.019813,263.426432,256.445680,528.490892,71.131364,-91.624224
27,0,0.000918,32.330542,1.570056,2.210358,0.001453,-0.331715,1.032832,0.000133,-18.094546,...,1425.655666,-17506.822776,1.366718,119.729855,44.019813,263.426432,256.445680,528.490892,71.131364,-91.624224
28,0,0.000335,25.657019,1.570796,2.035801,0.001488,-0.421914,0.291489,-0.002855,-3.730195,...,133.076605,-115.649573,1.262918,-950.815420,47.115005,61.670539,-115.617188,149.211053,49.851508,69.123357
29,0,0.000113,32.951365,1.570796,1.958556,0.000254,-0.114564,3.213071,-0.001460,-34.105903,...,235.028321,-215.054485,1.311617,137.790055,33.679659,1031.429480,4022.860369,382.439793,39.470431,143.926604
30,0,0.000177,35.260149,1.570796,2.098881,0.000218,-0.179396,6.773331,-0.000293,7.622038,...,-577.042761,1896.401663,1.083204,68.133509,24.184973,-244.099690,137.378501,-399.316349,33.899766,440.499396
31,1,0.000386,17.786723,1.570796,2.090887,0.000200,-0.062541,0.805777,0.001248,-18.284571,...,-429.323214,-1131.943733,1.544423,113.912606,48.960101,1237.065558,-1119.870742,-152.059668,75.297074,629.795377
32,1,0.000277,55.896183,1.570796,1.984409,0.000333,0.006946,0.632261,0.000000,-25.764363,...,-350.231137,7440.024995,1.548541,107.782458,54.823572,660.156178,-1765.712416,-162.640375,79.967754,1193.882845
33,0,0.000799,38.734272,1.570796,2.343438,0.000548,-0.174430,0.471414,0.000224,-6.769908,...,-222.941531,403.424766,1.120524,74.060181,20.016210,-155.449468,73.605945,-252.084647,48.948633,-511.864329
34,0,0.009722,103.367158,1.570796,2.241838,0.001342,0.112671,1.344355,0.002784,-2.901845,...,-58.723632,87.517247,1.104900,41.447670,19.176120,-47.989537,40.952201,-52.455042,172.140398,-100.888225
35,0,0.001515,30.110858,1.570796,2.356190,0.000486,-0.325487,1.031610,0.000599,-14.286388,...,-477.473066,-793.275780,1.377506,320.096221,76.865834,151.525478,-340.518929,-524.341063,75.183611,286.707656
36,0,0.002630,22.945788,1.570796,2.223186,0.000414,-0.045715,0.650093,0.000644,1.608364,...,326.710706,-144.777525,1.230305,3154.856673,57.971966,82.200807,-145.886441,383.897965,50.481371,54.829547
37,0,0.000319,53.545064,1.570796,2.057469,0.000892,-0.006346,0.166964,0.000153,-25.827646,...,-389.180163,-369.769000,1.226644,74.097433,21.929571,-245.186316,104.768654,19975.308604,53.913185,209.114146
38,0,0.000184,35.690312,1.570796,1.999382,0.000476,-0.214968,0.555675,0.000000,-3.636760,...,61038.534017,264.109748,1.446024,76.053871,26.809162,623.936201,182.808954,264.386721,43.231238,-178.432580
39,0,0.003416,10.500244,1.570796,2.004796,0.000461,-0.529648,0.183722,-0.001666,-20.082978,...,472.340046,764.447201,1.296876,97.605077,32.632122,573.614960,298.681719,154.471172,35.133229,-216.936801
40,0,0.001496,-1.277980,1.570796,2.182357,0.000518,-0.199580,1.201367,0.000000,-28.125549,...,-165.745673,-2093.530647,1.263096,92.481353,28.111989,1052.611845,651.032720,-91.775152,69.757347,249.472830
41,0,0.000854,22.403886,1.570796,2.387518,0.000509,0.015027,1.343871,0.000820,-11.183742,...,-564.235817,-527.834372,1.554851,153.771437,43.368914,-276.628274,260.287618,-419.017471,93.467299,477.620644
42,0,0.000057,50.383792,1.570796,5.353932,0.001706,-0.187770,0.187540,-0.002101,-2.650005,...,-162.434733,426.438629,1.092686,77.136131,29.923245,-301.442227,266.859875,-124.246745,108.234377,-664.951197

In [125]:
data_ff_HC = data_ff[data_ff['diagnosis']==0]
data_ff_dep = data_ff[data_ff['diagnosis']==1]

In [126]:
del data_ff_HC['diagnosis']
del data_ff_dep['diagnosis']

In [127]:
data_ff_test = data_ff
y = data_ff['diagnosis']
del data_ff_test['diagnosis']

In [128]:
r_value = []
p_value = []
mean_value_HC = []
std_value_HC = []
mean_value_dep = []
std_value_dep = []

In [129]:
features = list(data_ff_test.columns)

In [130]:
for feature in features:
    a = stats.pearsonr(data_ff_test[feature], y)[0]
    b = stats.pearsonr(data_ff_test[feature], y)[1]
    r_value.append(abs(a))
    p_value.append(b)
    mean_value_HC.append(np.mean(data_ff_HC[feature]))
    std_value_HC.append(np.std(data_ff_HC[feature]))
    mean_value_dep.append(np.mean(data_ff_dep[feature]))
    std_value_dep.append(np.std(data_ff_dep[feature]))

C:\Users\skiju\anaconda3\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))

In [131]:
statistical_ff = pd.DataFrame(columns=['name_column', '|r-value|', 'p-value', 'HC_mean', 'HC_std', 'dep_mean', 'dep_std'])

In [132]:
statistical_ff['name_column'] = features
statistical_ff['|r-value|'] = r_value
statistical_ff['p-value'] = p_value
statistical_ff['HC_mean'] = mean_value_HC
statistical_ff['HC_std'] = std_value_HC
statistical_ff['dep_mean'] = mean_value_dep
statistical_ff['dep_std'] = std_value_dep

In [133]:
statistical_ff.to_csv('.\dataset\statistical\stat_ff.csv')

# Concat all modalities

In [137]:
statistical_analysis = pd.concat([statistical_AU, statistical_eul, statistical_prob, statistical_ff], axis=0)

In [138]:
statistical_analysis

,name_column,|r-value|,p-value,HC_mean,HC_std,dep_mean,dep_std
0,AU01_mid_Absolute energy,0.022678,0.885228,297.096599,280.719671,280.924372,423.752479
1,AU01_mid_Area under the curve,0.035639,0.820511,3.956729,3.578449,3.644858,5.005329
2,AU01_mid_Autocorrelation,0.283366,0.065571,23.675136,30.034361,7.860902,7.956739
3,AU01_mid_Average power,0.077808,0.619938,19.868842,11.545548,21.933829,14.001060
4,AU01_mid_Centroid,0.122723,0.433037,7.091934,6.521866,5.451457,5.530448
...,...,...,...,...,...,...,...
14655,59_69angle_eve_rsd,0.374128,0.013454,116.031809,364.004756,568.743867,758.160854
14656,110_111angle_eve_rsd,0.040315,0.797425,201.449759,941.660407,370.365802,3159.637408
14657,64_124angle_eve_rsd,0.082760,0.597769,702.099057,3651.736529,168.873980,426.637712
14658,106_109angle_eve_rsd,0.039867,0.799634,72.220791,46.255291,68.874693,17.650703
14659,93_103angle_eve_rsd,0.191567,0.218470,-281.056230,1685.292219,300.770646,331.124853

In [143]:
statistical_analysis_reorderd = statistical_analysis.sort_values(by=['|r-value|'], ascending=False)

In [144]:
statistical_analysis_reorderd = statistical_analysis_reorderd.reset_index()

In [146]:
del statistical_analysis_reorderd['index']

In [153]:
statistical_analysis_reorderd['Depressive Episode Mean (SD)'] = 0
statistical_analysis_reorderd['Non-Depressive State Mean (SD)'] = 0

In [172]:
sub_set_statistical = statistical_analysis_reorderd.loc[0:500]

In [173]:
for sample in range(0, len(sub_set_statistical)):
    sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
    sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'

C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Depressive Episode Mean (SD)'].loc[sample] = str(round(sub_set_statistical['dep_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['dep_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_set_statistical['Non-Depressive State Mean (SD)'].loc[sample] = str(round(sub_set_statistical['HC_mean'].loc[sample], 2)) + ' (' + str(round(sub_set_statistical['HC_std'].loc[sample], 2)) + ')'
C:\Users\skiju\AppData\Local\Temp\ipykernel_8068\734779192.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


In [175]:
sub_set_statistical.to_csv('.\dataset\statistical\statistical_features500.csv')